- name: Module User
  hosts: all
  become: yes

  tasks:
    - name: Cr√©ation d'un User
      user:
        name: user
        shell: /bin/bash
        createhome: true
        group: sudo # Pour lui permettre le sudo
        uid: 1200 # Fixer l'UID
        state: present
        password: "{{ 'password' | password_hash('sha512') }}"

    - name: Suppression d'un user
      user:
        name: user
        state: absent